### ISSUE TITLE
Nz() function is completely missing

### ISSUE THREAD

**Issue by fns** [tmorehouse/hashids.vba#1]
Nz() is an MS Access only fx.

**Comment by tmorehouse** [comment]
I will investigate the issue.  I currently only use the module with MS Access, but haven't tested with other MS applications.

**Comment by fns** [comment]
Private Function Nz(data As Variant, Optional nullValue As Variant)
    If IsNull(data) Then
        If isMissing(nullValue) Then
            Nz = ""
        Else
            Nz = nullValue
        End If
    Else
        Nz = data
    End If
End Function

**Comment by tmorehouse** [comment]
Thanks,

I will incorporate this function into the next release.

**Comment by tmorehouse** [comment]
A private Nz() function has been added
