### ISSUE TITLE
Decoding does not work.

### ISSUE THREAD

**Issue by fns** [tmorehouse/hashids.vba#2]
Returns an array with zeros.

**Comment by tmorehouse** [comment]
I will investigate this

**Comment by tmorehouse** [comment]
I had a few typos in the untested decoding functions. This might fix the decoding issues.

**Comment by tmorehouse** [comment]
Latest commit includes fixes for decoding.

When decoding a has that contains a single number the result will be a `number` (`long`)

when decoding a hash that contains multiple numbers an `array` of the numbers will be returned.
