### ISSUE TITLE
Declaration issues

### ISSUE THREAD

**Issue by fns** [tmorehouse/hashids.vba#3]
Public Function EncodeHex(ByVal hexStr As String): variable c undeclared (string)

Public Function DecodeHex(ByVal hashStr As String) As Variant: num variable must be a Variant (because it is used in a For Each)

README.md, SYNOPSIS: 
number = hid.Decode('YDx');     '  123  - there is no ; line terminators in VBA and sting delimiters are " characters instead of '

Here is a proper test function:

Option Explicit

Sub testHashids()
    Dim hid As Hashids
    Dim hash As String, number As Long, numbers As Variant, i As Long

```
Set hid = New Hashids
hid.Params ("this is my salt")

' encrypt a single number
hash = hid.Encode(123)          '  "YDx"
Debug.Print "Encode 123:", hash

number = hid.Decode("YDx")     '  123
Debug.Print "Decode YDx:", number

' or a list
hash = hid.Encode(1, 2, 3)      ' "laHquq"
Debug.Print "Encode list 1,2,3:", hash

numbers = hid.Decode("laHquq")  ' (1, 2, 3)
Debug.Print "Decode laHquq:"
For i = LBound(numbers) To UBound(numbers)
    Debug.Print numbers(i)
Next i

' or an Array
hash = hid.Encode(Array(1, 2, 3)) ' "laHquq"
Debug.Print "Encode Array(1,2,3):", hash

numbers = hid.Decode("laHquq")  ' (1, 2, 3)
Debug.Print "Decode laHquq:"
For i = LBound(numbers) To UBound(numbers)
    Debug.Print numbers(i)
Next i
```

End Sub

Encoding/decoding now working properly.

**Comment by tmorehouse** [comment]
All fixed up (I think). Thanks for the help!

**Comment by tmorehouse** [comment]
Released a new version that supports the same integer range as the JavaScript version (2^53) by using numbers stored as Decimal types to get around VBA's 32bit longs

**Comment by fns** [comment]
Great!-)

**Comment by tmorehouse** [comment]
Let me know if you find any issues.
